server {
    listen 80;
    server_name seu_dominio_ou_ip.com;

    root /var/www/erp-loja/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|eot|ttf|otf)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, no-transform";
    }

    error_log /var/log/nginx/erp_loja_error.log;
    access_log /var/log/nginx/erp_loja_access.log;
}
